version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      ruby: 2.6

    commands:
     # Install CFN-Lint, taskcat, YAMLLint
      #- pip3 install cfn-lint taskcat yamllint

      # Install cfn-nag
      #- gem install cfn-nag

  pre_build:
    commands:
      # Validate Template
#      - aws cloudformation validate-template --template-body ./template.yaml
#      - yamllint --strict templates/workload.template
#      - cfn-lint -t sam/app/template.yaml
#      - cfn_nag --fail-on-warnings --output-format txt ./template.yaml

      # Run taskcat, strip color escape codes, output taskcat log files on STDOUT, and exit with result of taskcat
      #- |
      #  taskcat -c ci/taskcat.yml | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g"
      #  TASKCAT_RESULT=${PIPESTATUS[0]}
      #
      #  ls -1 taskcat_outputs/*.txt | while read LOG
      #  do
      #    echo
      #    echo "> $LOG"
      #    cat ${LOG}
      #  done
      #
      #  exit $TASKCAT_RESULT

  build:
    commands:
      - env
      - aws cloudformation package --template-file template.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged-template.yaml

artifacts:
  files: ./packaged-template.yaml


