AWSTemplateFormatVersion: "2010-09-09"
Description: Master template for pipeline experiments
Parameters:
  GitSourceRepo:
    Type: String
    Description: "Github Repository"
  GitBranch:
    Type: String
    Description: "Github Repository Branch"
  GitHubUser:
    Type: String
    Description: "Github Repository User"
  GitHubTokenSecretsManager:
    NoEcho: true
    Type: String
    Default: '{{resolve:secretsmanager:/quickstart/ekspipeline/githubtoken:SecretString:GHToken}}'
    Description: GitHub Token. Must be defined in AWS Secrets Manager. https://github.com/settings/tokens
  PipelineEmail:
    Type: String
    Description: "Email address for pipeline approval notifications"
  CodeBuildDockerImage:
    Type: String
    Description: "Docker Image for CodeBuild instance"
  TemplateConfigFileName:
    Type: String
    Description: Filename for template parameter configuration
  MasterTemplateFileName:
    Type: String
    Description: Filename for template parameter configuration

#test change for commitfafaf

Resources:
  InfrastructurePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-17j50869gmwc2/ab7873dc5ab228047b4c9be827cafbf5.template
      Parameters:
        PipelineEmail: !Ref PipelineEmail
        GitSourceRepo: !Ref GitSourceRepo
        GitBranch: !Ref GitBranch
        GitHubUser: !Ref GitHubUser
        CodeBuildDockerImage: !Ref CodeBuildDockerImage
        MasterStackTemplateName: !Sub ${AWS::StackName}
        TemplateConfigFileName: !Ref TemplateConfigFileName
        MasterTemplateFileName: !Ref MasterTemplateFileName