AWSTemplateFormatVersion: "2010-09-09"
Description: Master template for pipeline experiments
Parameters:
  GitSourceRepo:
    Type: String
    Description: "Github Repository"
  GitBranch:
    Type: String
    Description: "Github Repository Branch"
  GitHubUser:
    Type: String
    Description: "Github Repository User"
  GitHubTokenSecretsManager:
    NoEcho: true
    Type: String
    Default: '{{resolve:secretsmanager:/quickstart/ekspipeline/githubtoken:SecretString:GHToken}}'
    Description: GitHub Token. Must be defined in AWS Secrets Manager. -->https://github.com/settings/tokens
  PipelineEmail:
    Type: String
    Description: "Email address for pipeline approval notifications"
  CodeBuildDockerImage:
    Type: String
    Description: "Docker Image for CodeBuild instance"
  TemplateConfigLocation:
    Type: String
    Description: Filename for template parameter configuration

Resources:
  InfrastructurePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./Infrastructure/infrastructure-pipeline.yaml
      Parameters:
        PipelineEmail: !Ref PipelineEmail
        GitSourceRepo: !Ref GitSourceRepo
        GitBranch: !Ref GitBranch
        GitHubUser: !Ref GitHubUser
        CodeBuildDockerImage: !Ref CodeBuildDockerImage
        MasterStackTemplateName: !Sub ${AWS::StackName}
        TemplateConfigLocation: !Ref TemplateConfigLocation